# Generated by Django 5.0.4 on 2024-05-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_id_candidateprofile_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='image',
            field=models.ImageField(blank=True, upload_to='candidate_images'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='image',
            field=models.ImageField(blank=True, upload_to='company_images'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='resume',
            field=models.FileField(blank=True, upload_to='resumes'),
        ),
    ]
