# Generated by Django 5.0.4 on 2024-05-07 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_candidateprofile_image_companyprofile_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidateprofile',
            old_name='image',
            new_name='candidate_image',
        ),
        migrations.RenameField(
            model_name='companyprofile',
            old_name='image',
            new_name='company_image',
        ),
    ]
