# Generated by Django 5.0.4 on 2024-05-14 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_image_candidateprofile_candidate_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='candidate_image',
            field=models.ImageField(blank=True, null=True, upload_to='candidate_images'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_image',
            field=models.ImageField(blank=True, null=True, upload_to='company_images'),
        ),
    ]
