# Generated by Django 5.0.4 on 2024-06-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_candidateprofile_candidate_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='candidate_image',
            field=models.ImageField(blank=True, null=True, upload_to='candidate_images/'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='resume',
            field=models.FileField(blank=True, upload_to='resumes/'),
        ),
    ]
