# Generated by Django 5.0.4 on 2024-06-13 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='job_post_limit',
            field=models.IntegerField(default=0, help_text='Use 0 for unlimited job posts'),
        ),
    ]
