# Generated by Django 5.0.4 on 2024-06-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('Success', 'Success'), ('failed', 'Failed')], default='pending', max_length=50),
        ),
    ]
