# Generated by Django 5.0.3 on 2024-03-12 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='birth date')),
                ('location', models.CharField(max_length=255, verbose_name='location')),
                ('skills', models.CharField(blank=True, max_length=255, null=True, verbose_name='skills')),
                ('experience', models.CharField(blank=True, max_length=100, null=True, verbose_name='experience')),
                ('education', models.CharField(blank=True, max_length=255, null=True, verbose_name='education')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/', verbose_name='resume')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'candidate_profile',
                'verbose_name_plural': 'candidate_profiles',
                'db_table': 'candidate_profile',
            },
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='company_name')),
                ('industry', models.CharField(max_length=100, verbose_name='industry')),
                ('location', models.CharField(max_length=255, verbose_name='location')),
                ('website', models.URLField(blank=True, null=True, verbose_name='website')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'company_profile',
                'verbose_name_plural': 'company_profiles',
                'db_table': 'company_profile',
            },
        ),
    ]
