# Generated by Django 5.0.3 on 2024-03-16 13:30

import django.core.validators
import django.db.models.deletion
import job.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('job_type', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Internship', 'Internship')], default='Full Time', max_length=10)),
                ('education', models.CharField(choices=[('Higher Secondary', 'Higher Secondary'), ('Bachelors', 'Bachelors'), ('Master', 'Master'), ('Phd', 'Phd')], default='Bachelors', max_length=20)),
                ('it_industry', models.CharField(choices=[('Software Developer', 'Software Developer'), ('Web Developer', 'Web Developer'), ('Mobile App Developer', 'Mobile App Developer'), ('Game Developer', 'Game Developer'), ('Embedded Systems Developer', 'Embedded Systems Developer'), ('DevOps Engineer', 'Devops Engineer'), ('Quality Assurance Engineer', 'Quality Assurance Engineer'), ('Test Automation Engineer', 'Test Automation Engineer'), ('Frontend Developer', 'Frontend Developer'), ('Backend Developer', 'Backend Developer'), ('Full Stack Developer', 'Full Stack Developer'), ('Database Developer', 'Database Developer'), ('Cloud Engineer', 'Cloud Engineer'), ('Systems Engineer', 'Systems Engineer'), ('UI/UX Designer', 'Ui Ux Designer'), ('Software Architect', 'Software Architect'), ('Machine Learning Engineer', 'Machine Learning Engineer'), ('AI Developer', 'Ai Developer'), ('Robotics Engineer', 'Robotics Engineer'), ('Blockchain Developer', 'Blockchain Developer'), ('AR/VR Developer', 'Ar Vr Developer'), ('IoT Developer', 'Iot Developer'), ('Firmware Engineer', 'Firmware Engineer'), ('Security Engineer', 'Security Engineer'), ('ETL Developer', 'Etl Developer'), ('BI Developer', 'Business Intelligence Developer'), ('NLP Engineer', 'Natural Language Processing Engineer'), ('Data Scientist', 'Data Scientist'), ('Data Analyst', 'Data Analyst'), ('Big Data Engineer', 'Big Data Engineer'), ('Data Architect', 'Data Architect'), ('Statistical Analyst', 'Statistical Analyst'), ('Predictive Modeling Analyst', 'Predictive Modeler'), ('Deep Learning Engineer', 'Deep Learning Engineer'), ('Computer Vision Engineer', 'Computer Vision Engineer'), ('Quantitative Analyst', 'Quantitative Analyst'), ('Data Visualization Engineer', 'Operations Visualization Engineer'), ('Research Scientist (Data Science)', 'Research Scientist'), ('Data Mining Engineer', 'Data Mining Engineer'), ('Computational Linguist', 'Computational Linguist'), ('Analytics Engineer', 'Analytics Engineer')], default='Frontend Developer', max_length=40)),
                ('experience', models.CharField(choices=[('Fresher', 'No Experience'), ('1 Year', 'One Year'), ('2 Years', 'Two Years'), ('3 Years or More', 'Three Years Plus')], default='Fresher', max_length=20)),
                ('salary', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)])),
                ('positions', models.IntegerField(default=1)),
                ('last_date', models.DateTimeField(default=job.models.return_date_time)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.companyprofile')),
            ],
        ),
    ]
