# Generated by Django 5.0.4 on 2024-05-14 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='address',
            new_name='location',
        ),
    ]
