# Generated by Django 5.0.4 on 2024-05-20 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_rename_address_job_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='title_slug',
        ),
    ]
